function AlertsPanel({ alerts, onResolveAlert }) {
  return (
    <div className="panel">
      <div className="panel-header">
        <div>
          <h2>Alerts</h2>
          <p>Active and resolved incidents generated by the alert engine.</p>
        </div>
      </div>

      <div className="table">
        <div className="table-header alerts-header">
          <span>Service</span>
          <span>Type</span>
          <span>Status</span>
          <span>Count</span>
          <span>Action</span>
        </div>

        {alerts.length === 0 ? (
          <div className="empty">No alerts found.</div>
        ) : (
          alerts.map((alert) => (
            <div className="table-row alerts-row" key={alert.id}>
              <div>
                <strong>{alert.service}</strong>
                <p>{alert.message}</p>
              </div>

              <span className="muted">{alert.type}</span>

              <span className={`badge badge-${alert.status}`}>
                {alert.status}
              </span>

              <span>{alert.event_count || alert.eventCount || 1}</span>

              {alert.status === "open" ? (
                <button className="small" onClick={() => onResolveAlert(alert.id)}>
                  Resolve
                </button>
              ) : (
                <span className="muted">—</span>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
}

export default AlertsPanel;